version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - redis-net

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    networks:
      - redis-net
    volumes:
      - redis_insight:/db

volumes:
  mongodb_data:
  redis-data:
  redis_insight:
networks:
  redis-net:
